### ISSUE TITLE
Support of dynamic Availability Zone for Public IPs

### ISSUE THREAD

**Issue by r2ronoha** [Azure/terraform-azurerm-loadbalancer#38] opened 2021-06-14 09:52 UTC
With the [2.63.0 version](https://registry.terraform.io/providers/hashicorp/azurerm/2.63.0) of azurerm, there is a new parameter [availability_zone](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.63.0/azurerm/internal/services/network/public_ip_resource.go#L64) replacing the old zone, being set by default to `Zone-Redundant`.

There are location where that is not supported, which leads to TF failing to create the LB Public IP

```
Error: creating/updating Public Ip Address: (Name "tate-publicIP" / Resource Group "switzerlandnorth-fut-dc"): network.PublicIPAddressesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="LocationNotSupportAvailabilityZones" Message="The resource 'Microsoft.Network/publicIPAddresses/tate-publicIP' does not support availability zones at location 'switzerlandnorth'."

  on .terraform/modules/k3s.workers_lb/main.tf line 6, in resource "azurerm_public_ip" "azlb":
   6: resource "azurerm_public_ip" "azlb" {
```

Would it be possible to add a variable to populate it dynamically in the [resource](https://github.com/Azure/terraform-azurerm-loadbalancer/blob/master/main.tf#L11)?

**Comment by r2ronoha** [comment] 2021-07-09 07:22
Hi

Any thoughts on this issue?

**Comment by callumhester** [comment] 2021-11-01 15:40
Hi,

Did you ever resolve this issue as I have come across this within my Terraform Script?

**Comment by callumhester** [comment] 2021-11-08 09:09
To fix this, I added a availability_zone = "No-Zone" argument to my AppGW IP address block

**Comment by r2ronoha** [comment] 2021-12-08 08:15
> To fix this, I added a availability_zone = "No-Zone" argument to my AppGW IP address block

I tried that, the issue is No-Zone is not supported in all regions.

**Comment by richard087** [comment] 2021-12-09 00:17
This issue will impact any use of Public IPs via the Cloud Adoption Framework. It's particularly relevant in the CAF context because it effects new users.

**Comment by Lddeiva** [comment] 2021-12-17 08:44
I did some testing and this happens when the sku is ```Standard```. 

Following code works,

```
resource "azurerm_public_ip" "example3" {​​​​​​​​
  name                = "acceptanceTestPublicIp3"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Static"
  sku                 = "Standard"
  availability_zone   = "No-Zone"


  tags = {​​​​​​​​
    environment = "Production"
  }​​​​​​​​
}​​​​​​​​
```

but the following code doesn't.

```
resource "azurerm_public_ip" "example4" {​​​​​​​​
  name                = "acceptanceTestPublicIp4"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  allocation_method   = "Static"
  sku                 = "Standard"


  tags = {​​​​​​​​
    environment = "Production"
  }​​​​​​​​
}​​​​​​​​
```

So, we need to specify the attribute ```availability_zone   = "No-Zone"``` if our SKU is ```Standard``` and the region doesn't support availability zones. Because, the Standard SKU Public IP Addresses that do not specify a zone are zone redundant by default.

**Comment by Lddeiva** [comment] 2021-12-17 08:47
@r2ronoha - FYI.

**Comment by lintaonz** [comment] 2022-06-08 04:22
I faced this issue as well. The problem is the `azurerm_public_ip. azlb` [line 11](https://github.com/Azure/terraform-azurerm-loadbalancer/blob/master/main.tf#L11). There has no way I can specify [availability_zone](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.63.0/azurerm/internal/services/network/public_ip_resource.go#L64) in the module.

So when I try to deploy the `azurerm-loadbalancer` to a region doesn't support availability zones, it will fail.

Could you add a new variable called `frontend_public_ip_availability_zone`, please?

**Comment by r2ronoha** [comment] 2022-09-21 07:09
Hi
Any progress on this issue?

**Comment by lonegunmanb** [comment] 2022-09-21 09:28
Hi @r2ronoha sorry for the late reply. This module is outdated and need heavily modernization reshaping. We're working on a new CI system to boost that and our first try is [aks module](https://github.com/Azure/terraform-azurerm-aks). We would modify this module when we have bandwidth. Thanks for your issue, I hope we can reshape this module asap.

**Comment by jiaweitao001** [comment] 2023-02-03 03:06
Hi, I have done some testing against the latest version of this resource. Looks like the parameters are different, now `availability_zone` is no longer configurable. Will close this issue.

**Closed by jiaweitao001** 2023-02-03 03:06 UTC
