### ISSUE TITLE
Error in deploying public load balancer

### ISSUE THREAD

**Issue by foreverXZC** [Azure/terraform-azurerm-loadbalancer#15] opened 2018-07-02 07:48 UTC
I tried to deploy a load balancer on Azure both in public and private case. I think your work is really fascinating because the resources are quite useful. However, when I am trying the public usage, such errors occur:
module.mylb.azurerm_lb.azlb: "frontend_ip_configuration.0.private_ip_address" is not a valid IP4 address: ""
module.mylb.azurerm_lb.azlb: Can not parse "frontend_ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure Id: parse : empty url
These errors indicate that I have to config private ip address and subnet id. Nevertheless, public load balancer actually does not need these parameters. After I download all source code and remove "subnet_id", "private_ip_address" and "private_ip_address_allocation" in "frontend_ip_configuration", everything seems to be correct.
I wonder whether it's my fault that I use this module incorrectly, or there really exist some defects in this module. I am looking forward to hearing from you. Thanks a lot!

**Comment by dberuben** [comment] 2018-07-13 20:21
You can solve the second issue with :

>  module.mylb.azurerm_lb.azlb: Can not parse "frontend_ip_configuration.0.subnet_id" as a resource id: Cannot parse Azure Id: parse : empty url

  `frontend_subnet_id                     = "${module.network.vnet_subnets[0]}"`

**Comment by Joncak** [comment] 2018-07-18 16:58
Hi @foreverXZC , use the previous azure provider it looks like azure make few changes on the lb resource.

```
provider "azurerm" {
  version = "1.7"
}
```

**Comment by alambike** [comment] 2018-07-19 08:01
I think is related to this issue in Terraform AzureRM provider:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/1470

**Comment by yupwei68** [comment] 2020-08-03 07:07
Hi @foreverXZC , thanks for opening this issue. Currently with the latest release, I could not reproduce your error. Sorry that I have to close this issue. Please try our latest release.

**Closed by yupwei68** 2020-08-03 07:07 UTC
Labels: help wanted, microsoft/P3
